spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


#okta configuraton for API Gateway

okta:
  oauth2:
    issuer: https://dev-21471692.okta.com/oauth2/default
    audience: api://default
    client-id: 0oajwtbve53b0BEhV5d7
    client-secret: oIrJxkDJiAFq1ueFN50uJy4nHZhTXzt1oXTxl5uBt-ZFDI4BWKf-ncWRxw2t8WA-
    scopes: openid, profile, email, offline_access